### ISSUE TITLE
Question about num_calibration

### ISSUE THREAD

**Issue by TortoiseHam** [p-lambda/verified_calibration#1]
Hi, thanks for making this library - it's super convenient. One question about the PlattBinnerMarginalCalibrator (and I suppose the other calibrators as well). What is the purpose of the num_calibration argument? it seems like it's only being used to assert that a minimum number of samples have been provided, but what is the point of that? Does it have any usages apart from the single assert?

**Comment by AnanyaKumar** [comment]
Yup that's the only usage - probably would've been better to not have it! Thanks for the question, and for pointing this out.

**Comment by TortoiseHam** [comment]
Cool, thanks for confirming
